import type { Metadata } from 'next'

import Layout from "@/components/Layout"

import MainProvider from '../providers/MainProvider'
import Favicons from '@/providers/HeadProvider/Favicons'

import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'K-CINEMA',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactElement
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=5"
        />
        <Favicons />
        <meta name="theme-color" content={'#181B1E'} />
        <meta name="msapplication-navbutton-color" content={'#181B1E'} />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content={'#181B1E'}
        />
      </head>
      <body>
        <MainProvider>
          <Layout>
            {children}
          </Layout>
        </MainProvider>
      </body>
    </html>
  )
}